export const AppSettings = Object.freeze({
    'URL_API': 'https://www.safecert.com.vn/api.gateway/DANH_MUC/',
    //'URL_API': 'http://192.168.11.15:8080/DMUC_MYSQL/DANH_MUC/',
    //'URL_API': 'http://192.168.11.27:8181/DMUC_MYSQL/DANH_MUC/',
    'no_image_promotion': 'assets/imgs/no-image-gift.png',
    'icon_discount': 'assets/icon/discount.png',
    'no_image_comp': 'assets/imgs/no-image-restaurant.png',
    //'google_api_key': 'AIzaSyCjB1Kh7OstaDns8ie6uPysWEWa_vwS3iw',
    'google_api_key': 'AIzaSyAy7cVxGwJb7HuewbnwUQgRsvYQdzvAnOE',
    'bg_login': 'assets/imgs/background-5.jpg',
    'logo_app': 'assets/imgs/km24_logo.png',
    'no_avatar': 'assets/imgs/no-avatar.png',
    'marker_start': 'assets/icon/marker-start.png',
    'marker_end': 'assets/icon/marker-end.png',
    'app_version': '1.0.15',
    //'oneSignal_appID': '387a97cf-e887-4e0d-9284-2068c62b3011',                                                                                                                                            
    'oneSignal_appID': '463d7601-70bf-43cc-ac74-53f41104916f',
    'oneSignal_gg_project_number': '773035484854',
    'app_name_push': 'muonangi_merchant',
    'merchant_id': '200'
});
